plugins {
    id 'java-library'
    id 'maven-publish'
    id 'uk.jamierocks.propatcher' version '2.0.1'
}

import com.ancientmc.acpgen.tasks.*
import com.ancientmc.acpgen.tasks.csv.*
import com.ancientmc.acpgen.util.*
import uk.jamierocks.propatcher.task.*

apply from: ('update.gradle')

group = 'com.ancientmc'

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net' }
    maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven/' }
}

dependencies {
    implementation 'net.minecraftforge:srgutils:0.5.4'
}

// Java 8 required for compiling and running old Minecraft.
tasks.withType(JavaCompile).configureEach {
    javaCompiler = javaToolchains.compilerFor {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.register('easyUpdate', EasyRun) { runName = 'update' }
tasks.register('easyIntermediate', EasyRun) { runName = 'intermediate' }
tasks.register('easyUnzip', EasyRun) { runName = 'unzip' }
tasks.register('easyLaunch', EasyRun) { runName = 'launch' }
tasks.register('easyPublish', EasyRun) { runName = 'publish' }

subprojects {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.neoforged.net' }
        maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven/' }
    }

    configurations {
        inheritance
        jarsplitter
        rosetta
        forgeart
        mcinjector
        fernflower
        vineflower
    }

    dependencies {
        inheritance 'net.neoforged.installertools:installertools:3.0.2:fatjar'
        jarsplitter 'net.neoforged.installertools:jarsplitter:3.0.2:fatjar'
        rosetta "com.ancientmc:rosetta:$rosetta_version:all"
        forgeart 'net.neoforged:AutoRenamingTool:2.0.8:all'
        mcinjector 'de.oceanlabs.mcp:mcinjector:4.1-am'
        fernflower 'com.ancientmc:fernflower:1.0'
        vineflower 'org.vineflower:vineflower:1.11.1'
    }

    tasks.register('downloadJson', Download) {
        src = Json.getJsonUrl(file(Paths.VERSION_MANIFEST), project.name)
        dest = file(Paths.JSON)
    }

    tasks.register('downloadClient', Download) {
        dependsOn downloadJson
        src = Json.getJarUrl(file(Paths.JSON), 'client')
        dest = file(Paths.BASE_JAR)
    }

    tasks.register('downloadLibraries', DownloadLibraries) {
        dependsOn downloadJson
        def list = Arrays.asList(file(Paths.JSON), file(Paths.JARDEP_JSON))
        jsons = list
        libs = file(Paths.DIR_LIBRARIES)
    }

    tasks.register('downloadNatives', DownloadNatives) {
        dependsOn downloadJson
        urls = Json.getNativeUrls(file(downloadJson.dest))
        output = file(Paths.DIR_NATIVES)
    }

    tasks.register('extractInheritance', JavaExec) {
        dependsOn downloadClient
        mainClass = 'net.neoforged.installertools.ConsoleTool'
        classpath = files(project.configurations.named('inheritance'))
        args('--task', 'EXTRACT_INHERITANCE', '--input', Paths.BASE_JAR, '--output', Paths.INHERITANCE)
    }

    // Only generate if the version to update is radically different than the previous one.
    // Otherwise we'll just match and update. Also, make sure to check the inheritance map first for any access errors so inheritance is intact.
    tasks.register('generateTsrg', JavaExec) {
        dependsOn downloadClient
        mainClass = 'com.ancientmc.rosetta.Rosetta'
        classpath = files(project.configurations.named('rosetta'))
        args('generate', Paths.ROSETTA_CFG, Paths.BASE_JAR, Paths.INHERITANCE, Paths.INTERMEDIATE_TSRG, Paths.IDS)
    }

    tasks.register('split', JavaExec) {
        dependsOn downloadClient
        mainClass = 'net.neoforged.jarsplitter.ConsoleTool'
        classpath = files(project.configurations.named('jarsplitter'))
        args('--input', Paths.BASE_JAR, '--slim', Paths.SLIM_JAR, '--extra', Paths.EXTRA_JAR, '--srg', Paths.INTERMEDIATE_TSRG)
    }

    tasks.register('verify', VerifyMappings) {
        dependsOn split
        jar = file(Paths.SLIM_JAR)
        tsrg = file(Paths.INTERMEDIATE_TSRG)
        log = file('mappings/verify.txt')
    }

    tasks.register('obfInject', ObfuscateInjectFiles) {
        intermediateTsrg = file(Paths.INTERMEDIATE_TSRG)
        intermediateAccess = file('inject/intermediate/access_intermediate.txt')
        intermediateExceptions = file('inject/intermediate/exceptions_intermediate.txt')
        obfuscatedAccess = file(Paths.ACCESS)
        obfuscatedExceptions = file(Paths.EXCEPTIONS)
    }

    tasks.register('mcinject', JavaExec) {
        dependsOn split
        mainClass = 'de.oceanlabs.mcp.mcinjector.MCInjector'
        classpath = files(project.configurations.named('mcinjector'))
        args('--in', Paths.SLIM_JAR, '--out', Paths.INJECT_JAR, '--lvt=LVT', '--acc', Paths.ACCESS, '--exc', Paths.EXCEPTIONS, '--blacklist', Paths.BLACKLIST)
    }

    tasks.register('deobfIntermediate', JavaExec) {
        dependsOn mcinject
        mainClass = 'net.neoforged.art.Main'
        classpath = files(project.configurations.named('forgeart'))
        args('--input', Paths.INJECT_JAR, '--output', Paths.SRG_JAR, '--map', Paths.INTERMEDIATE_TSRG, '--src-fix', '--strip-sigs')
    }

    tasks.register('writeCsvs', WriteCsvs) {
        dependsOn (split, extractInheritance)
        tsrg = file(Paths.INTERMEDIATE_TSRG)
        classCsv = file('mappings/csv/classes.csv')
        fieldCsv = file('mappings/csv/fields.csv')
        methodCsv = file('mappings/csv/methods.csv')
        paramCsv = file('mappings/csv/params.csv')
    }

    tasks.register('applyCsvs', ApplyCsvs) {
        csvDirectory = project.file('mappings/csv/')
        inTsrg = file(Paths.INTERMEDIATE_TSRG)
        outTsrg = file(Paths.CUNEIFORM_TSRG)
    }

    tasks.register('exportStats', ExportMappingStats) {
        dependsOn applyCsvs
        csvDirectory = file('mappings/csv/')
        statsCsv = file('mappings/stats.csv')
    }

    tasks.register('deobfMapped', JavaExec) {
        dependsOn (applyCsvs, exportStats, mcinject)
        mainClass = 'net.neoforged.art.Main'
        classpath = files(project.configurations.named('forgeart'))
        args('--input', Paths.INJECT_JAR, '--output', Paths.CNF_JAR, '--map', Paths.CUNEIFORM_TSRG, '--src-fix=JAVA')
    }

    tasks.register('decompile', JavaExec) {
        dependsOn deobfMapped
        mainClass = 'org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler'
        classpath = files(project.configurations.named('fernflower'))
        args('-rbr=0', '-rsy=0', '-asc=1', '-dgs=0', '-jvn=1', '-ind=    ', Paths.CNF_JAR, Paths.DECOMP_JAR)
    }

    tasks.register('unzip', Copy) {
        dependsOn decompile
        from zipTree(file(Paths.DECOMP_JAR))
        into file(Paths.DIR_SRC)
    }

    tasks.register('extractResources', Copy) {
        dependsOn unzip
        from zipTree(file(Paths.EXTRA_JAR))
        into file(Paths.DIR_RESOURCES)
        exclude 'META-INF/*'
    }

    tasks.register('backupSrc', Copy) {
        dependsOn unzip
        from fileTree(Paths.DIR_SRC)
        into file('run/original_src')
    }

    tasks.register('createPatchesDir') {
        def dir = file('patches/')
        dir.mkdir()
    }

    tasks.register('patchesMake', MakePatchesTask) {
        dependsOn createPatchesDir
        rootDir file('run/original_src/')
        target file(Paths.DIR_SRC)
        patches file('patches/')
    }

    tasks.register('patchesApply', ApplyPatchesTask) {
        dependsOn unzip
        target file(Paths.DIR_SRC)
        patches file('patches/')
    }

    tasks.register('buildClasses', JavaCompile) {
        dependsOn (downloadLibraries, downloadNatives)
        dependsOn file(Paths.DIR_PATCHES).exists() ? patchesApply : [:]
        source = files(Paths.DIR_SRC).asFileTree
        classpath = files(Paths.DIR_LIBRARIES).asFileTree
        sourceCompatibility = '8'
        targetCompatibility = '8'
        options.compilerArgs = ['-g:none']
        destinationDirectory = file('build/classes/')
    }

    tasks.register('buildJar', Jar) {
        dependsOn (buildClasses, extractResources)
        archiveBaseName = 'built'
        destinationDirectory = project.file('run/')

        manifest { attributes('Main-Class': 'acp.client.Start') }
        from ('build/classes')
        from ('build/resources')
        from files('run/lib/').asFileTree.collect { it.isDirectory() ? it : zipTree(it) }
    }

    tasks.register('runClient', JavaExec) {
        dependsOn !file(Paths.BUILT_JAR).exists() ? buildJar : [:]
        mainClass = 'acp.client.Start'
        classpath = files(Paths.BUILT_JAR)
        systemProperty 'java.library.path', Paths.DIR_NATIVES
    }

    tasks.register('makeZip', Zip) {
        archiveBaseName = 'versions'
        archiveVersion = project.name
        destinationDirectory = file('build/zip/')

        from (Paths.CUNEIFORM_TSRG)
        from (Paths.EXCEPTIONS) { into 'inject' }
        from (Paths.ACCESS) { into 'inject' }
        from (Paths.BLACKLIST) { into 'inject' }
        from (Paths.JARDEP_JSON)
        from ('run/src/main/java/acp/') { into 'start/acp' }
        from (Paths.DIR_PATCHES) { into 'patches' }
    }

    publishing {
        publications.register("version${project.name}", MavenPublication) {
            artifact makeZip
            groupId = rootProject.group
            artifactId = 'versions'
            version = project.name
            pom {
                name = 'ACP Version Data'
                description = 'Version data for ACP processes, generated via AcpGen'
                url = 'https://github.com/ancientmc/AcpGen'
                licenses {
                    license {
                        name = 'GNU General Public License Version 2' // until our license is updated and Cuneiform's license figured out
                        url = 'https://www.gnu.org/licenses/old-licenses/gpl-2.0.txt'
                    }
                }
                developers {
                    developer {
                        id = 'moist-mason'
                        name = 'Mason'
                        url = 'https://github.com/moist-mason'
                    }
                }
            }
        }
        repositories {
            maven {
                name = 'ancientmc-maven'
                url = '../ancientmc-maven'
            }
        }
    }
}