plugins {
    id 'java-library'
}

group = 'com.ancientmc'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net' }
    maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven/' }
}

import com.ancientmc.acpconfig.tasks.*
import com.ancientmc.acpconfig.tasks.csv.*
import com.ancientmc.acpconfig.util.*

subprojects {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.neoforged.net' }
        maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven/' }
    }

    configurations {
        inheritance
        jarsplitter
        forgeart
        mcinjector
    }

    dependencies {
        inheritance "net.neoforged.installertools:installertools:3.0.2:fatjar"
        jarsplitter 'net.neoforged.installertools:jarsplitter:3.0.2:fatjar'
        forgeart 'net.neoforged:AutoRenamingTool:2.0.8:all'
        mcinjector 'de.oceanlabs.mcp:mcinjector:4.1-am'
    }

    version = project.name

    tasks.register('downloadJson', Download) {
        src = Json.getJsonUrl(file(Paths.VERSION_MANIFEST), version)
        dest = file(Paths.JSON)
    }

    tasks.register('downloadClient', Download) {
        dependsOn downloadJson
        src = Json.getJarUrl(file(Paths.JSON), 'client')
        dest = file(Paths.BASE_JAR)
    }

    tasks.register('downloadLibraries', DownloadLibraries) {
        dependsOn downloadJson
        def list = Collections.singletonList(file(Paths.JSON))
        jsons = list
        libs = file(Paths.DIR_LIBRARIES)
    }

    tasks.register('extractInheritance', JavaExec) {
        dependsOn downloadClient
        mainClass = 'net.neoforged.installertools.ConsoleTool'
        classpath = files(project.configurations.named('inheritance'))
        args('--task', 'EXTRACT_INHERITANCE', '--input', Paths.BASE_JAR, '--output', Paths.INHERITANCE)
    }

    // Only generate if the version to update is radically different than the previous one.
    // Otherwise we'll just match and update. Also, make sure to check the inheritance map first for any access errors so inheritance is intact.
    tasks.register('writeTsrg', WriteTsrg) {
        dependsOn downloadClient
        jar = file(Paths.BASE_JAR)
        tsrg = file(Paths.INTERMEDIATE_TSRG)
        inheritanceJson = file(Paths.INHERITANCE)
        ids = file('mappings/ids.csv')
    }

    tasks.register('split', JavaExec) {
        dependsOn downloadClient
        mainClass = 'net.neoforged.jarsplitter.ConsoleTool'
        classpath = files(project.configurations.named('jarsplitter'))
        args('--input', Paths.BASE_JAR, '--slim', Paths.SLIM_JAR, '--extra', Paths.EXTRA_JAR, '--srg', Paths.INTERMEDIATE_TSRG)
    }

    tasks.register('verify', VerifyMappings) {
        dependsOn split
        jar = file(Paths.SLIM_JAR)
        tsrg = file(Paths.INTERMEDIATE_TSRG)
    }

    tasks.register('mcinject', JavaExec) {
        dependsOn split
        mainClass = 'de.oceanlabs.mcp.mcinjector.MCInjector'
        classpath = files(project.configurations.named('mcinjector'))
        args('--in', Paths.SLIM_JAR, '--out', Paths.INJECT_JAR, '--lvt=LVT', '--exc', Paths.EXC, '--blacklist', Paths.BLACKLIST)
    }

    tasks.register('deobfIntermediate', JavaExec) {
        dependsOn mcinject
        mainClass = 'net.neoforged.art.Main'
        classpath = files(project.configurations.named('forgeart'))
        args('--input', Paths.INJECT_JAR, '--output', Paths.SRG_JAR, '--map', Paths.INTERMEDIATE_TSRG, '--src-fix', '--strip-sigs')
    }

    tasks.register('writeCsvs', WriteCsvs) {
        dependsOn (split, extractInheritance)
        tsrg = file(Paths.INTERMEDIATE_TSRG)
        classCsv = file('mappings/csv/classes.csv')
        fieldCsv = file('mappings/csv/fields.csv')
        methodCsv = file('mappings/csv/methods.csv')
        paramCsv = file('mappings/csv/params.csv')
    }

    def csvs = ['classes', 'fields', 'methods', 'params']
    csvs.each { table ->
        int i = csvs.indexOf(table)
        def name = table.capitalize()
        def temp = projectDir.path + '/mappings/temp/temp-' + i + '.tsrg'

        // This is garbage and needs to be refactored
        // I don't know why but the projectDir.path is needed here for it to run.
        def applyCsv = tasks.register("apply${name}", ApplyCsv) {
            csv = file(projectDir.path + '/mappings/csv/' + table + ".csv")
            inTsrg = i == 0 ? file(projectDir.path + '/' + Paths.INTERMEDIATE_TSRG) : file(temp)
            outTsrg = i == 3 ? file(projectDir.path + '/' + Paths.CUNEIFORM_TSRG) : file(projectDir.path + "/mappings/temp/temp-" + (i + 1) + ".tsrg")
            mustRunAfter i != 0 ? "apply${csvs.get(i - 1).capitalize()}" : [:]
        }
    }

    tasks.register('applyAllCsv') { dependsOn(applyClasses, applyFields, applyMethods, applyParams) }

    tasks.register('deobfMapped', JavaExec) {
        dependsOn (applyAllCsv, mcinject)
        mainClass = 'net.neoforged.art.Main'
        classpath = files(project.configurations.named('forgeart'))
        args('--input', Paths.INJECT_JAR, '--output', Paths.CNF_JAR, '--map', Paths.CUNEIFORM_TSRG, '--src-fix', '--strip-sigs')
    }
}

apply from: ('update.gradle')