plugins {
    id 'java-library'
    id "de.undercouch.download" version "5.6.0"
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
    maven { url = 'https://maven.neoforged.net' }
    maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven/' }
}

dependencies {
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'commons-io:commons-io:2.18.0'
    implementation 'org.ow2.asm:asm:9.7.1'
    implementation 'org.ow2.asm:asm-tree:9.7.1'
    implementation 'net.minecraftforge:mapping-verifier:2.0.8:fatjar'
    implementation 'net.minecraftforge:srgutils:0.5.4'
}

import com.ancientmc.acpconfig.tasks.*
import com.ancientmc.acpconfig.tasks.csv.*
import com.ancientmc.acpconfig.util.*

ext {
    VERSION_MANIFEST = 'data/version_manifest.json' // TODO: replace with custom manifest that includes versions not in launcher
}

tasks.register('downloadVersionManifest', Download) {
    src 'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json'
    dest VERSION_MANIFEST
}

subprojects {
    repositories {
        mavenCentral()
        maven { url = 'https://maven.neoforged.net' }
        maven { url = 'https://github.com/ancientmc/ancientmc-maven/raw/maven/' }
    }

    configurations {
        inheritance
        jarsplitter
        forgeart
        mcinjector
    }

    dependencies {
        inheritance "net.neoforged.installertools:installertools:3.0.2:fatjar"
        jarsplitter 'net.neoforged.installertools:jarsplitter:3.0.2:fatjar'
        forgeart 'net.neoforged:AutoRenamingTool:2.0.8:all'
        mcinjector 'de.oceanlabs.mcp:mcinjector:4.1-am'
    }

    ext {
        VERSION = project.name
    }

    // Init paths
    Paths paths = new Paths(VERSION)

    tasks.register('downloadJson', Download) {
        dependsOn rootProject.downloadVersionManifest
        src Json.getJsonUrl(downloadVersionManifest.dest, VERSION).toString()
        dest paths.JSON
    }

    tasks.register('downloadClient', Download) {
        dependsOn downloadJson
        src Json.getJarUrl(file(paths.JSON), "client").toString()
        dest paths.BASE_JAR
    }

    tasks.register('downloadLibraries', DownloadLibraries) {
        dependsOn downloadJson
        def list = Collections.singletonList(file(Paths.JSON))
        jsons = list
        libs = file(paths.DIR_LIBRARIES)
    }

    tasks.register('extractInheritance', JavaExec) {
        dependsOn downloadClient
        mainClass = 'net.neoforged.installertools.ConsoleTool'
        classpath = files(project.configurations.named('inheritance'))
        args('--task', 'EXTRACT_INHERITANCE', '--input', paths.BASE_JAR, '--output', paths.INHERITANCE)
    }

    // Only generate if the version to update is radically different than the previous one.
    // Otherwise we'll just match and update. Also, make sure to check the inheritance map first for any access errors so inheritance is intact.
    tasks.register('writeTsrg', WriteTsrg) {
        dependsOn downloadClient
        jar = file(paths.BASE_JAR)
        tsrg = file(paths.INTERMEDIATE_TSRG)
        inheritanceJson = file(paths.INHERITANCE)
    }

    tasks.register('split', JavaExec) {
        dependsOn(downloadClient, writeTsrg)
        mainClass = 'net.neoforged.jarsplitter.ConsoleTool'
        classpath = files(project.configurations.named('jarsplitter'))
        args('--input', paths.BASE_JAR, '--slim', paths.SLIM_JAR, '--extra', paths.EXTRA_JAR, '--srg', paths.INTERMEDIATE_TSRG)
    }

    tasks.register('verify', VerifyMappings) {
        dependsOn(split, writeTsrg)
        jar = file(paths.SLIM_JAR)
        tsrg = file(paths.INTERMEDIATE_TSRG)
    }

    tasks.register('mcinject', JavaExec) {
        dependsOn split
        mainClass = 'de.oceanlabs.mcp.mcinjector.MCInjector'
        classpath = files(project.configurations.named('mcinjector'))
        args('--in', paths.SLIM_JAR, '--out', paths.INJECT_JAR, '--lvt=LVT', '--exc', paths.EXC, '--blacklist', paths.BLACKLIST)
    }

    tasks.register('deobfIntermediate', JavaExec) {
        dependsOn mcinject
        mainClass = 'net.neoforged.art.Main'
        classpath = files(project.configurations.named('forgeart'))
        args('--input', paths.INJECT_JAR, '--output', paths.SRG_JAR, '--map', paths.INTERMEDIATE_TSRG, '--src-fix', '--strip-sigs')
    }

    tasks.register('writeCsvs', WriteCsvs) {
        dependsOn(split, extractInheritance)
        tsrg = file(paths.INTERMEDIATE_TSRG)
        classCsv = file("mappings/csv/classes.csv")
        fieldCsv = file("mappings/csv/fields.csv")
        methodCsv = file("mappings/csv/methods.csv")
        paramCsv = file("mappings/csv/params.csv")
    }

    def csvs = ['classes', 'fields', 'methods', 'params']
    csvs.each { table ->
        int i = csvs.indexOf(table)
        def name = table.capitalize()
        def temp = projectDir.path + "/mappings/temp/temp-" + i + ".tsrg"

        // This is garbage and needs to be refactored
        // I don't know why but the projectDir.path is needed here for it to run.
        def applyCsv = tasks.register("apply${name}", ApplyCsv) {
            csv = file(projectDir.path + "/mappings/csv/" + table + ".csv")
            inTsrg = i == 0 ? file(projectDir.path + '/' + paths.INTERMEDIATE_TSRG) : file(temp)
            outTsrg = i == 3 ? file(projectDir.path + '/' + paths.CUNEIFORM_TSRG) : file(projectDir.path + "/mappings/temp/temp-" + (i + 1) + ".tsrg")
            mustRunAfter i != 0 ? "apply${csvs.get(i - 1).capitalize()}" : [:]
        }
    }

    tasks.register('applyAllCsv') { dependsOn(applyClasses, applyFields, applyMethods, applyParams) }

    tasks.register('deobfMapped', JavaExec) {
        dependsOn applyAllCsv
        mainClass = 'net.neoforged.art.Main'
        classpath = files(project.configurations.named('forgeart'))
        args('--input', paths.INJECT_JAR, '--output', paths.CNF_JAR, '--map', paths.CUNEIFORM_TSRG, '--src-fix', '--strip-sigs')
    }
}