rootProject.name = 'AcpGen'

def versions = new File(rootDir, '/data/versions/')

// Group version projects in subdirectories based on dev phase.
def phases = ['classic', 'indev', 'infdev', 'alpha', 'beta', 'release', 'snapshot']
phases.each { phase ->
    def phaseDir = new File(versions, '/' + phase + '/')
    if (phaseDir.exists()) {
        phaseDir.eachDir() { verDir ->
            def proj = rootDir.toPath().relativize(verDir.toPath()).toFile()
            include proj.path
            project(':' + proj.path).name = verDir.name
        }
    }
}