import com.ancientmc.acpconfig.tasks.UpdateTsrg

repositories {
    mavenCentral()
}

dependencies {

}

ext {
    OLD = 'c0.0.13a_03'
    NEW = 'c0.0.14a_08'
    OLD_DIR = String.join('/', 'data/versions', phase(OLD as String), OLD)
    NEW_DIR = String.join('/', 'data/versions', phase(NEW as String), NEW)
    MATCH = 'data/matches/' + OLD + '-' + NEW + '.match'
}

tasks.register('updateTsrg', UpdateTsrg) {
    oldIds = file(OLD_DIR + '/mappings/ids.csv')
    oldTsrg = file(OLD_DIR + '/mappings/intermediate.tsrg')
    match = file(MATCH)
    newJar = file(NEW_DIR + '/game/jars/client.jar')
    inheritanceJson = file(NEW_DIR + '/inheritance_map.json')
    newTsrg = file(NEW_DIR + '/mappings/intermediate.tsrg')
    newIds = file(NEW_DIR + '/mappings/ids.csv')
}

static def phase(String ver) {
    if (ver.startsWith('c')) return 'classic'
    if (ver.startsWith('in-')) return 'indev'
    if (ver.startsWith('inf-')) return 'infdev'
    if (ver.startsWith('a')) return 'alpha'
    if (ver.startsWith('b')) return 'beta'
    if (ver.matches('[0-9]+w[0-9]+[a-z]+')) return 'snapshot'
    return 'release'
}

