import com.ancientmc.acpconfig.tasks.csv.UpdateCsv
import com.ancientmc.acpconfig.tasks.UpdateTsrg

repositories {
    mavenCentral()
}

configurations {
    rosetta
}

dependencies {
    rosetta "com.ancientmc:rosetta:$rosetta_version:all"
}

ext {
    OLD = 'c0.0.13a_03'
    NEW = 'c0.0.14a_08'
    OLD_DIR = String.join('/', 'data/versions', phase(OLD as String), OLD)
    NEW_DIR = String.join('/', 'data/versions', phase(NEW as String), NEW)
    NEW_CFG = String.join('/', NEW_DIR, 'mappings/rosetta.cfg')
    NEW_JAR = String.join('/', NEW_DIR, 'game/jars/client.jar')
    NEW_INHERITANCE = String.join('/', NEW_DIR, 'inheritance_map.json')
    OLD_TSRG = String.join('/', OLD_DIR, 'mappings/intermediate.tsrg')
    NEW_TSRG = String.join('/', NEW_DIR, 'mappings/intermediate.tsrg')
    OLD_IDS = String.join('/', OLD_DIR, 'mappings/ids.csv')
    NEW_IDS = String.join('/', NEW_DIR, 'mappings/ids.csv')
    OLD_CSV_DIR = String.join('/', OLD_DIR, 'mappings/csv/')
    NEW_CSV_DIR = String.join('/', NEW_DIR, 'mappings/csv/')
    MATCH = 'data/matches/' + OLD + '-' + NEW + '.match'
}

/*
tasks.register('updateTsrg', UpdateTsrg) {
    group = 'update'
    oldIds = file(OLD_DIR + '/mappings/ids.csv')
    oldTsrg = file(OLD_DIR + '/mappings/intermediate.tsrg')
    match = file(MATCH)
    newJar = file(NEW_DIR + '/game/jars/client.jar')
    inheritanceJson = file(NEW_DIR + '/inheritance_map.json')
    newTsrg = file(NEW_DIR + '/mappings/intermediate.tsrg')
    newIds = file(NEW_DIR + '/mappings/ids.csv')
}
 */

tasks.register('updateTsrg', JavaExec) {
    group = 'update'
    mainClass = 'com.ancientmc.rosetta.Rosetta'
    classpath = files(project.configurations.named('rosetta'))
    args('update', NEW_CFG, NEW_JAR, NEW_INHERITANCE, OLD_TSRG, OLD_IDS, MATCH, NEW_TSRG, NEW_IDS)
}

// Params are not updated because they aren't matched between versions, and are instead freshly generated in the TSRG with their parent methods.
def csvs = ['classes', 'fields', 'methods', 'params']
csvs.each { table ->
    def updateCsv = tasks.register("update${table.capitalize()}Csv", UpdateCsv) {
        group = 'update'
        input = file(OLD_CSV_DIR + '/' + table + '.csv')
        blankOutput = file(NEW_CSV_DIR + '/' + table + '.csv')
        output = file(NEW_CSV_DIR + '/' + table + '.csv')
    }
}

/**
 * new version -> writeCsvs *before* running this!
 */
tasks.register('updateAllCsvs') {
    group = 'update'
    dependsOn(updateClassesCsv, updateMethodsCsv, updateFieldsCsv, updateParamsCsv)
}

static def phase(String ver) {
    if (ver.startsWith('c')) return 'classic'
    if (ver.startsWith('in-')) return 'indev'
    if (ver.startsWith('inf-')) return 'infdev'
    if (ver.startsWith('a')) return 'alpha'
    if (ver.startsWith('b')) return 'beta'
    if (ver.matches('[0-9]+w[0-9]+[a-z]+')) return 'snapshot' // snapshot format -> <YY>w<WW>x, where x is the release on that week.
    return 'release'
}

